### PR TITLE
Toggle-switch activity

### PR DESCRIPTION
**Pull request by viancamaulion**
toggle-switch-ezgif com-crop

## https://codepen.io/viamaulion/pen/gOyzOPB
* ⌛ You have 15 minutes to implement this, take your time (but not too much)!
* 💅 Feel free to embellish and make it pretty!
* 📦 Some basic CSS is provided for you. There are some `TODO` comments in there to help you out.
* 🧙 You can search online if you get stuck.
* 🎉 When you're done, `Fork` 🍴 the Codepen page and share with us the URL.

<p align='center'>* * *</p>

## Tips and hints

- Only edit the `input`'s css selector.
- Use [`&` nesting selector](https://developer.mozilla.org/en-US/docs/Web/CSS/Nesting_selector) like `&:checked` and `&:after`.
- Use [sibling selectors](https://www.browserstack.com/guide/sibling-selectors-in-css) like `~` and `+`.
- [To Do] During darkmode, change the:
   1. Label's background and its `&:after`'s horizontal position
   2. SVG's colors
   3. Div's background

### CODE REVIEW

**Comment by raaims** [comment]
Will reopen when the time is right (char)

**Comment by redlpd** [comment]
https://codepen.io/redlpd/pen/PogVLVq

**Comment by kyljmn0** [comment]
https://codepen.io/Kyle-Jemino/pen/wvZNObW

**Comment by janpatrickpalacio** [comment]
https://codepen.io/janpatrick-dev/pen/WNWPmPo

**Comment by kiembully** [comment]
https://codepen.io/Kim-Klinton-Vale/pen/RwOvdOb

**Comment by raaims** [comment]
https://codepen.io/raaims/pen/LYvqvPv?editors=1100

**Comment by xinjo21** [comment]
https://codepen.io/El-Razin-Jo/pen/QWPYoYd

**Comment by kerdaddyb** [comment]
https://codepen.io/kerdaddyb/pen/gOyqEyp

**Pull request merged**
