### PR TITLE
Focus Variants - Tailwind CSS

### PR DESCRIPTION
**Pull request by vincent-mashupgarage**
tailwind-focus-variants

## https://play.tailwindcss.com/5IEmKhHkKX

- ⌛ You have 15 minutes to implement this, take your time (but not too much)!
- 💅 Feel free to embellish and make it pretty!
- 📦 Some basic CSS is provided for you. There are some `TODO` comments in there to help you out.
- 🧙 You can search online if you get stuck.
- 🎉 When you're done, `Fork` 🍴 the Tailwind page and share with us the URL.
- After opening the link, just straight up edit the thing it's alright it will create a new link for your own copy. Then just click - `Share`  and reply it here to share your own work!

<p align='center'>* * *</p>

## Tips and hints

- Use "focus-within" on the outer form container to highlight the entire card whenever any field inside it (such as the name, email, or password input) is active.
- Use "focus" on each input field to give individual feedback for users. This will make it clear which specific field is active.
- Use "focus-visible" on the "Sign Up" button to show focus styles only for keyboard users, without affecting mouse clicks.

### CODE REVIEW

**Comment by kerdaddyb** [comment]
https://play.tailwindcss.com/6vsDblF5MK

**Comment by janpatrickpalacio** [comment]
https://play.tailwindcss.com/CuRI6unEqL

**Comment by xinjo21** [comment]
https://play.tailwindcss.com/Tp8JHLCgb6

**Comment by kiembully** [comment]
https://play.tailwindcss.com/7iZK3aI0xn

**Comment by Mykvll** [comment]
https://play.tailwindcss.com/7NMfBGOOjH

**Comment by zedrictron** [comment]
https://play.tailwindcss.com/8rinAkS9gl

**Comment by jomelmadia** [comment]
https://play.tailwindcss.com/lqiI0xm0BS

**Pull request merged**
