### PR TITLE
Responsive Table activity

### PR DESCRIPTION
**Pull request by ejllovido**
responsive-table

## https://codepen.io/ejllovido/pen/eYowYMN
* ⌛ You have 15 minutes to implement this, take your time (but not too much)!
* 💅 Feel free to embellish and make it pretty!
* 📦 Some basic CSS is provided for you. There are some `TODO` comments in there to help you out.
* 🧙 You can search online if you get stuck.
* 🎉 When you're done, `Fork` 🍴 the Codepen page and share with us the URL.

<p align='center'>* * *</p>

## Tips and hints

- Make the table responsive.
- Use flex property such as `flex-basis`, `flex-grow` and `flex-wrap`

### CODE REVIEW

**Comment by janpatrickpalacio** [comment]
https://codepen.io/janpatrick-dev/pen/eYaYZzg

**Comment by kiembully** [comment]
https://codepen.io/Kim-Klinton-Vale/pen/MWdWywe

**Comment by AdyCastEX** [comment]
https://codepen.io/adycastueras/pen/OJYJNJq

**Comment by kerdaddyb** [comment]
https://codepen.io/kerdaddyb/pen/KKLKzWz?editors=1100

**Comment by redlpd** [comment]
https://codepen.io/redlpd/pen/OJYJNPq

**Pull request merged**
