### PR TITLE
Stopwatch Activity

### PR DESCRIPTION
**Pull request by janpatrickpalacio**
stopwatch

## Fork me: https://codepen.io/janpatrick-dev/pen/JjVJVmL
* ⌛ You have 15 minutes to implement this, take your time (but not too much)!
* 💅 Feel free to embellish and make it pretty!
* 📦 Some basic CSS is provided for you. There are some `TODO` comments in there to help you out.
* 🧙 You can search online if you get stuck.
* 🎉 When you're done, `Fork` 🍴 the Codepen page and share with us the URL.

<p align='center'>* * *</p>

## Tips and hints

- Only use `keyframes` for making animations.
- The `transform` property will be used mostly in this activity for doing animations.

### CODE REVIEW

**Comment by kiembully** [comment]
https://codepen.io/Kim-Klinton-Vale/pen/ExJvWay?editors=1100

**Comment by AdyCastEX** [comment]
https://codepen.io/adycastueras/pen/LYvjWEy

**Comment by notco** [comment]
https://codepen.io/notco/pen/vYMJxEp

**Comment by ornops** [comment]
https://codepen.io/SnorlaxCodes/pen/OJGjpVB

**Comment by torisutanjon** [comment]
https://codepen.io/tristanjohn/pen/yLroMJy?editors=0110

**Review by raaims — APPROVED** [review]

**Pull request merged**
