### PR TITLE
Group Hover and SubGrid - TailwindCSS

### PR DESCRIPTION
**Pull request by torisutanjon**
blitz-recording

Link for examination is here, I used the Tailwind CSS own playground instead of CodePen, because the tailwind's CDN does not yet supports the topic.

https://play.tailwindcss.com/R4spkOriHS

⌛ You have 15 minutes to implement this, take your time (but not too much)!
💅 Feel free to embellish and make it pretty!
📦 Some basic CSS is provided for you. There are some TODO comments in there to help you out.
🧙 You can search online if you get stuck.
🎉 When you're done, Fork 🍴 the Codepen page and share with us the URL.

Just populate the needed tailwind codes on the keywords `ADD_TAILWIND_CODE_HERE` found in the HTML Tab

After opening the link, just straight up edit the thing it's alright it will create a new link for your own copy. Then just click `Share` and reply it here to share your own work!

### CODE REVIEW

**Comment by kerdaddyb** [comment]
Closing this PR for now. Will open it again when the stars align. 🥰

**Comment by jomelmadia** [comment]
https://play.tailwindcss.com/ZoGVuUt0yR

**Comment by josephvillanueva** [comment]
https://play.tailwindcss.com/NMn9QJosMB

**Comment by xinjo21** [comment]
https://play.tailwindcss.com/iwl0frJsVQ

**Comment by Mykvll** [comment]
https://play.tailwindcss.com/UEpSICCRIK

**Comment by kiembully** [comment]
https://play.tailwindcss.com/bn4GLED4lQ

**Comment by bfgonzalez** [comment]
https://play.tailwindcss.com/xe49pck1uR

**Comment by kerdaddyb** [comment]
https://play.tailwindcss.com/hlPLni4fUG

**Pull request merged**
