### PR TITLE
DVD Screensaver

### PR DESCRIPTION
**Pull request by raaims**
image

### Fork me: https://codepen.io/raaims/pen/jXNNMz

* ⌛ You have 15 minutes to implement this, take your time (but not too much)!
* 💅 Feel free to embellish and make it pretty!
* 📦 Some basic CSS is provided for you. There are some `TODO` comments in there to help you out.
* 🧙 You can search online if you get stuck.
* 🎉 When you're done, `Fork` 🍴 the Codepen page and share with us the URL.

<p align='center'>* * *</p>

## Tips and hints

- Do not use positioning properties! (`left`, `right`, `top`, and `bottom`)
- Use the `transform` attribute. You have `translate`, `scale`, `rotate`, and more. Go wild!

### CODE REVIEW

**Comment by kerdaddyb** [comment]
https://codepen.io/kerdaddyb/pen/mdoaado?editors=1100

**Comment by kyljmn0** [comment]
https://codepen.io/Kyle-Jemino/pen/WNmLLvQ?editors=1111

**Comment by torisutanjon** [comment]
https://codepen.io/tristanjohn/pen/RwdEEwv

**Comment by viancamaulion** [comment]
https://codepen.io/Vianca-Andrea-Maulion/pen/ExMGGab

**Comment by xinjo21** [comment]
https://codepen.io/El-Razin-Jo/pen/poYqqvE

**Comment by kiembully** [comment]
https://codepen.io/Kim-Klinton-Vale/pen/WNmLLbQ

**Pull request merged**
