### PR TITLE
Container queries

### PR DESCRIPTION
**Pull request by leonellcruz7**
css-container-query

## https://codepen.io/leonellcruz7/pen/zYQzZaX

* ⌛ You have 15 minutes to implement this, take your time (but not too much)!
* 💅 Feel free to embellish and make it pretty!
* 📦 Some basic CSS is provided for you. There are some `TODO` comments in there to help you out.
* 🧙 You can search online if you get stuck.
* 🎉 When you're done, `Fork` 🍴 the Codepen page and share with us the URL.

<p align='center'>* * *</p>

## Tips and hints

- Make the card inside the element with grid-container class responsive.
- Use `container queries` and `flex-direction` property to control card responsiveness.

### CODE REVIEW

**Comment by janpatrickpalacio** [comment]
https://codepen.io/janpatrick-dev/pen/rNgwGQx

**Comment by redlpd** [comment]
https://codepen.io/redlpd/pen/YzbQrvE

**Comment by kiembully** [comment]
https://codepen.io/Kim-Klinton-Vale/pen/rNgwGrO

**Comment by viancamaulion** [comment]
https://codepen.io/viancamaulion/pen/LYoLzBy

**Comment by kerdaddyb** [comment]
https://codepen.io/kerdaddyb/pen/dyERVKz?editors=1100

**Comment by Mykvll** [comment]
https://codepen.io/mikmik28/pen/qBGjPKr

**Comment by ejllovido** [comment]
https://codepen.io/ejllovido/pen/qBGjPMm?editors=1100

**Comment by josephvillanueva** [comment]
https://codepen.io/josephseph/full/bGyRoKO

**Comment by josephvillanueva** [comment]
https://codepen.io/josephseph/pen/bGyRoKO

**Pull request merged**
