### PR TITLE
CSS Dropdown

### PR DESCRIPTION
**Pull request by bfgonzalez**
css-dropdown

## https://codepen.io/bianca-mashup/pen/vYwLdGX?editors=1100

* ⌛ You have 15 minutes to implement this, take your time (but not too much)!
* 💅 Feel free to embellish and make it pretty!
* 📦 Some basic CSS is provided for you. There are some `TODO` comments in there to help you out.
* 🧙 You can search online if you get stuck.
* 🎉 When you're done, `Fork` 🍴 the Codepen page and share with us the URL.

<p align='center'>* * *</p>

## Tips and hints

- Use the `:focus-within` css pseudo-class
- Submenu should only be visible when the parent menu or one of the submenu items is focused

### CODE REVIEW

**Comment by kerdaddyb** [comment]
https://codepen.io/kerdaddyb/pen/ExzyboP?editors=1100

**Comment by gel-mashup** [comment]
https://codepen.io/gel-mashup/pen/gOJMXGe?editors=1100

**Comment by janpatrickpalacio** [comment]
https://codepen.io/janpatrick-dev/pen/QWREOqY?editors=1100

**Comment by xinjo21** [comment]
https://codepen.io/El-Razin-Jo/pen/JjqKOrR

**Comment by AdyCastEX** [comment]
https://codepen.io/adycastueras/pen/zYQBPPv

**Comment by viancamaulion** [comment]
https://codepen.io/viancamaulion/pen/vYwKWee?editors=1100

**Comment by ianDrilon07** [comment]
https://codepen.io/ianDrilon07/pen/KKLMyXY?editors=1100

**Comment by torisutanjon** [comment]
https://codepen.io/tristanjohn/pen/BaezmwP?editors=1100

**Comment by jomelmadia** [comment]
https://codepen.io/jomelmadia/pen/LYoZOzx?editors=1100

**Comment by Mykvll** [comment]
https://codepen.io/mikmik28/pen/yLWJPzd?editors=1100

**Pull request merged**
