### PR TITLE
Gradient and Keyframes - Core Memories

### PR DESCRIPTION
**Pull request by zedrictron**
css-core-memories

## https://codepen.io/zedrictron/pen/RwzWGpj

- ⌛ You have 15 minutes to implement this, take your time (but not too much)!
- 💅 Feel free to embellish and make it pretty!
- 📦 Some basic CSS is provided for you. There are some `TODO` comments in there to help you out.
- 🧙 You can search online if you get stuck.
- 🎉 When you're done, `Fork` 🍴 the Codepen page and share with us the URL.

<p align='center'>* * *</p>

## Tips and hints

- Use `gradients` for each core memory orb.
- Create multiple `keyframes` for different core memory animations.
- Animate the core memory orbs in any way you want! ( Make it spin or Zoom _Inside out_ )

### CODE REVIEW

**Comment by ejllovido** [comment]
https://codepen.io/ejllovido/pen/WNqrzBd

**Comment by kerdaddyb** [comment]
https://codepen.io/kerdaddyb/pen/bGPEvzr

**Comment by viancamaulion** [comment]
https://codepen.io/viancamaulion/pen/Yzowamw

**Comment by Mykvll** [comment]
https://codepen.io/mikmik28/pen/vYqLRqG

**Comment by josephvillanueva** [comment]
https://codepen.io/josephseph/pen/MWMKVdq

**Pull request merged**
