### PR TITLE
Hamburger menu

### PR DESCRIPTION
**Pull request by redlpd**
hamburger-menu

## Fork me: https://codepen.io/redlpd-mg/pen/vYMYNVM

* ⌛ You have 15 minutes to implement this, take your time (but not too much)!
* 💅 Feel free to embellish and make it pretty!
* 📦 Some basic CSS is provided for you. There are some `TODO` comments in there to help you out.
* 🧙 You can search online if you get stuck.
* 🎉 When you're done, `Fork` 🍴 the Codepen page and share with us the URL.

<p align='center'>* * *</p>

## Tips and hints

- Use checkbox.
- Clicking the label should activate the input.
- Visibilty (`display` and `opacity`).
- Use `transform` with `translate` and `rotate` (Discussed in the previous blitz `DVD Screensaver`).

### CODE REVIEW

**Comment by raaims** [comment]
https://codepen.io/raaims/pen/oNONLrm?editors=1100

**Review by janpatrickpalacio — COMMENTED** [review]
https://codepen.io/janpatrick-dev/pen/YzMzWob

**Comment by AdyCastEX** [comment]
https://codepen.io/adycastueras/pen/RwOwRzX?editors=1100

**Comment by ashleeeeeeyyyyyy** [comment]
https://codepen.io/ashleeeeeeyyyyy/pen/VwNwjJN

**Comment by viancamaulion** [comment]
https://codepen.io/Vianca-Andrea-Maulion/pen/OJGJXKy

**Comment by KennedydeVera** [comment]
https://codepen.io/Kennedy-De-Vera/pen/rNbNLXJ

**Pull request merged**
