### PR TITLE
Modal

### PR DESCRIPTION
**Pull request by raaims**
image

## Fork me: https://codepen.io/kirblitz/pen/ExJgPvx

- ⌛ You have 15 minutes to implement this, take your time (but not too much)!
- 💅 Feel free to embellish and make it pretty!
- 📦 Some basic CSS is provided for you. There are some `TODO` comments in there to help you out.
- 🧙 You can search online if you get stuck.
- 🎉 When you're done, `Fork` 🍴 the Codepen page and share with us the URL.

<p align='center'>* * *</p>

## Tips and hints

- Use `transform` and `position properties` to position the elements.
- Don't forget to put `pointer-events` property.
- Use the `:target` pseudo element. Go wild!

### CODE REVIEW

**Comment by AdyCastEX** [comment]
https://codepen.io/adycastueras/pen/rNbMMGE

**Comment by notco** [comment]
https://codepen.io/notco/pen/PogGGJO

**Comment by janpatrickpalacio** [comment]
https://codepen.io/janpatrick-dev/pen/gOywwXG

**Comment by kiembully** [comment]
https://codepen.io/Kim-Klinton-Vale/pen/WNWGGXK

**Comment by viancamaulion** [comment]
https://codepen.io/Vianca-Andrea-Maulion/pen/bGJwwoM

**Comment by tkevinmattt** [comment]
https://codepen.io/tkevinmatt/pen/eYoddjq

**Pull request merged**
