### PR TITLE
Radio button carousel

### PR DESCRIPTION
**Pull request by xinjo21**
radio-button

## https://codepen.io/El-Razin-Jo/pen/YzbeJjb

- ⌛ You have 15 minutes to implement this, take your time (but not too much)!
- 💅 Feel free to embellish and make it pretty!
- 📦 Some basic CSS is provided for you. There are some `TODO` comments in there to help you out.
- 🧙 You can search online if you get stuck.
- 🎉 When you're done, `Fork` 🍴 the Codepen page and share with us the URL.

<p align='center'>* * *</p>

## Tips and hints

- Hide the radio button
- Use `~`(general sibling combinator) to style the elements based on the state of the radio inputs
- Use `tranform` for positioning of left, right and center cards

### CODE REVIEW

**Comment by kerdaddyb** [comment]
https://codepen.io/kerdaddyb/pen/VwOQJOm?editors=1100

**Comment by redlpd** [comment]
https://codepen.io/redlpd/pen/xxNWxBb

**Comment by janpatrickpalacio** [comment]
https://codepen.io/janpatrick-dev/pen/bGyvGZv

**Comment by ejllovido** [comment]
https://codepen.io/ejllovido/pen/RwmMwdp?editors=1100

**Comment by kiembully** [comment]
https://codepen.io/Kim-Klinton-Vale/pen/OJYvJqO

**Comment by Mykvll** [comment]
https://codepen.io/mikmik28/pen/VwOXwRK

**Comment by zedrictron** [comment]
https://codepen.io/zedrictron/pen/RwmMNNg

**Comment by raaims** [comment]
https://codepen.io/raaims/pen/qBGoBvO?editors=1100

**Comment by viancamaulion** [comment]
https://codepen.io/viamaulion/full/ExzExMY

**Pull request merged**
